from typing import List, Dict, Any
from gliner2 import GLiNER2
from interfaces import EntityExtractor, QueryState

class GlinerExtractor(EntityExtractor):
    def __init__(self, model_name="fastino/gliner2-base-v1"):
        self.model = GLiNER2.from_pretrained(model_name)
        # Removed hardcoded self.base_labels. The pipeline is now 100% dynamic.

    def process(self, state: QueryState) -> List[Dict[str, Any]]:
        # Rely entirely on the labels dynamically generated by the LLM Router
        combined_labels = {}
        
        if isinstance(state.potential_labels, dict):
            for k, v in state.potential_labels.items():
                combined_labels[k.lower()] = v
        elif isinstance(state.potential_labels, list):
            # Fallback if the LLM messes up and returns a list instead of a dict
            for label in state.potential_labels:
                combined_labels[label.lower()] = f"Entities related to {label}"
        
        # Fail-safe: If the LLM router failed to generate any labels, default to a generic PII catch-all
        if not combined_labels:
            print("Warning: No potential labels received from Router. Using fallback.")
            combined_labels = {"pii": "Any sensitive or personally identifiable information"}
            
        # Use GLiNER 2's advanced features
        result = self.model.extract_entities(
            state.raw_query, 
            combined_labels,
            include_confidence=True,
            include_spans=True
        )
        
        extracted = []
        for label, entities_list in result.get("entities", {}).items():
            for e in entities_list:
                # Kept the 0.40 threshold to prevent overmasking
                if e.get("confidence", 0.0) > 0.40:
                    extracted.append({
                        "token": e["text"],
                        "label": label,
                        "score": e.get("confidence", 0.0),
                        "start": e.get("start", 0),
                        "end": e.get("end", 0)
                    })
                
        return extracted